# Generated by Django 4.2.2 on 2023-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platemodel',
            name='license_plate',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
