# Generated by Django 4.2.2 on 2023-07-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0003_platemodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platemodel',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='platemodel',
            name='published_date',
        ),
        migrations.AddField(
            model_name='platemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='platemodel',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='img/license_plates/'),
        ),
    ]
