# Generated by Django 4.2.2 on 2023-07-11 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plate', '0004_rename_created_date_platemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userplate', to=settings.AUTH_USER_MODEL),
        ),
    ]
