# Generated by Django 4.2.2 on 2023-07-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0006_platecapturedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platecapturedmodel',
            name='image_license',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='img/plate_captured/'),
        ),
    ]
