# Generated by Django 4.2.2 on 2023-07-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, max_length=300, upload_to='img/profile_pics'),
        ),
    ]
